<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require_once '../../../users/init.php';  //make sure this path is correct!
if (!securePage($_SERVER['PHP_SELF'])){die();}

if(!isset($_SESSION))
  {
    session_start();
  }
if($_SESSION['faq'] != "true"){
   //send them back
   header("Location: .");
}
 ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <?php include '../../assets/headerCenter.php'; ?>
    <meta content="Welcome to the Hull Seals, Elite Dangerous's Premier Hull Repair Specialists!" name="description">
    <title>Quiz: FAQ | The Hull Seals</title>
</head>
<body>
    <div id="home">
      <?php include '../../assets/menuCode.php';?>
        <section class="introduction container">
	    <article id="intro3">
        <h1>Quiz: Frequently Asked Questions</h1>
        <br />
        <form action="results.php" method = "post">
          <div class="input-group mb-3">
            <p>1.What of these star classes are NOT fuelable?<br />
              <input type="radio" name="fuel" id="fuel" required="" value="A"> G-Class<br>
              <input type="radio" name="fuel" id="fuel" required="" value="B"> C-Class<br>
              <input type="radio" name="fuel" id="fuel" required="" value="C"> B-Class<br>
              <input type="radio" name="fuel" id="fuel" required="" value="D"> F-Class<br>
            </p>
          </div>
          <div class="input-group mb-3">
            <p>2. What is one of the proper formats for systems generated by Frontier?<br />
              <input type="radio" name="format" required="" id="format" value="A"> LL-L L#-#<br>
              <input type="radio" name="format" required="" id="format" value="B"> LL-L ##-#<br>
              <input type="radio" name="format" required="" id="format" value="C"> LL-# L#-#<br>
              <input type="radio" name="format" required="" id="format" value="D"> L#-L LL-#<br>
            </p>
          </div>
          <div class="input-group mb-3">
            <p>3. What should you do if a client is too close to a star for a navlock drop?<br />
              <input type="radio" name="starbright" required="" id="starbright" value="A"> Have the client relog to move away from the Star. <br>
              <input type="radio" name="starbright" required="" id="starbright" value="B"> Execute the "Tactical Face Plant" (TFP)<br>
              <input type="radio" name="starbright" required="" id="starbright" value="C"> Inform your Dispatcher.<br>
              <input type="radio" name="starbright" required="" id="starbright" value="D"> Ask the Client to move away from the Star.<br>
            </p>
          </div>
          <button class="btn btn-primary" type="submit">Submit</button>
        </form>
      </article>
            <div class="clearfix"></div>
        </section>
    </div>
    <?php include '../../assets/footer.php'; ?>
</body>
</html>
